### ISSUE TITLE
Uploading badges returns 500 when user session has expired

### ISSUE THREAD

**Issue by jarrett** [mozilla/openbadges-backpack#1010]
To reproduce, log in to the application. Visit the upload page and keep it open. Let the session expire (or force expiration). Submit the upload form.

The controller assumes the user object still exists and therefore crashes on a TypeError. It would be better to check that for the user object and redirect if the object isn't present. (Which the application does for most other actions.) Here's the error:

```
Express
500 TypeError: Cannot call method 'get' of undefined
at userBadgeUpload (/var/www/openbadges/controllers/backpack.js:383:41)
at callbacks (/var/www/openbadges/node_modules/express/lib/router/index.js:161:37)
at param (/var/www/openbadges/node_modules/express/lib/router/index.js:135:11)
at pass (/var/www/openbadges/node_modules/express/lib/router/index.js:142:5)
at Router._dispatch (/var/www/openbadges/node_modules/express/lib/router/index.js:170:5)
at Object.router (/var/www/openbadges/node_modules/express/lib/router/index.js:33:10)
at /var/www/openbadges/node_modules/newrelic/lib/transaction/tracer.js:180:22
at ErrorTracer.monitor (/var/www/openbadges/node_modules/newrelic/lib/error.js:192:12)
at Tracer.monitor (/var/www/openbadges/node_modules/newrelic/lib/transaction/tracer.js:178:28)
at Object.monitored (/var/www/openbadges/node_modules/newrelic/lib/transaction/tracer.js:159:17)
```

**Comment by mattdigitalme** [comment]
@auralon related to #1027 ?

**Comment by auralon** [comment]
Well, @mattdigitalme, it's related in the sense that it would contribute to the errors listed by @cadecairos.

It's a separate issue though, and no doubt still needs addressing!
