### ISSUE TITLE
Backpack Frequently Timing Out When Adding or Issuing a Badge

### ISSUE THREAD

**Issue by kayaelle** [mozilla/openbadges-backpack#1027]
While adding a badge it stalls and returns a "NetworkError: 504 Gateway Timeout - http://backpack.openbadges.org/backpack/badge" error.

Same happens when issuing a badge. The badge is recognized but when clicking on "yes" to accept it returns "NetworkError: 504 Gateway Timeout - https://backpack.openbadges.org/issuer/assertion". It does actually add the badge.

**Comment by mhawksey** [comment]
Any update on this? If you fill in this form with your Backpack email it sent a link to a Google Site where you should be able to claim a badge associated to your email https://docs.google.com/a/hawksey.info/forms/d/1IKfJQGu1spJyTpkPWYL8TlXcRFQxm8gv8ZMATXcVQWU/viewform

I'm still getting a 504

**Comment by cmcavoy** [comment]
Sorry for the delay @mhawksey the holidays got in the way.

@jdotpz any ideas here? I'm really not sure what to look into next. I can't figure out if this is an app issue, or a server issue.

**Comment by shahparthiv** [comment]
hey,

Any updates in this issue ?

**Comment by mattdigitalme** [comment]
@auralon We should be in the clear with this one - be good for anyone attached to this issue to let us know if issues are still occurring with badge uploads

**Comment by auralon** [comment]
@mattdigitalme, it'd be worth checking the error rates since the recent deployment, in comparison to what was hosted before.  Maybe @cadecairos can offer some insight into whether the overall error rate has dropped.

I'm not sure if this particular bug is still an issue, but it's not one I've encountered.

**Comment by cadecairos** [comment]
I'm still seeing plenty of errors. Now that it's been deployed for a week, I'll compare it to the week before and post the results here.

**Comment by cadecairos** [comment]
The week pre-deployment:

![pre-deploy-backpack](https://cloud.githubusercontent.com/assets/438003/21235635/95a1c38a-c2c5-11e6-8f37-ce7138695b26.png)

This is the week after:

![post-deploy-backpack](https://cloud.githubusercontent.com/assets/438003/21235641/9bfbd3d8-c2c5-11e6-8a62-316066e39fa4.png)

Either there's more traffic, causing more errors, or stability has decreased.

I think the former is more likely, as in the period before launch, we saw ~7,000,000 log lines, and the week after saw ~9,000,000 log lines

**Comment by auralon** [comment]
@cadecairos interesting to see.  Could you send me anonymised partials of the logs that relate to these 503 and 500 errors.  Maybe we can track down the cause.  

I've noticed that sending a badge that already exists in the backpack triggers an error, which is something that needs addressing at some point.

**Comment by cadecairos** [comment]
This is interesting:

```
host app web.1 - VerificationError: no response returned from child process
host app web.1 -     at IncomingMessage.<anonymous> (/app/node_modules/passport-persona/lib/passport-persona/strategy.js:114:29)
host app web.1 -     at IncomingMessage.emit (events.js:117:20)
host app web.1 -     at _stream_readable.js:944:16
host app web.1 -     at process._tickCallback (node.js:458:13)
```

**Comment by cadecairos** [comment]
That log was for this path/method: `method=POST path="/auth/browserid"`

**Comment by cadecairos** [comment]
Here's a breakdown of errors by path since deployment:?

![errorsbypath](https://cloud.githubusercontent.com/assets/438003/21237915/f075b7e0-c2ce-11e6-9aac-8cad33106bb2.png)

**Comment by auralon** [comment]
So, it looks like the bulk of errors relate to persona (/auth/browserid).

I'll take a look into this.

**Comment by auralon** [comment]
Thanks for that @cadecairos!

**Comment by mattdigitalme** [comment]
@cadecairos @auralon Thanks both - I'm not going to pretend I understand all of this - so will leave you both to it :)

**Comment by mattdigitalme** [comment]
@cadecairos Are you able to provide another snapshot or error logs to see if we're moving in the right direction?
