### ISSUE TITLE
Issuer API is turning 1.0-compliant badges into 0.5 badges

### ISSUE THREAD

**Issue by ottonomy** [mozilla/openbadges-backpack#1029]
Hi, backpack team. I created this assertion and hosted it, built a page to use the Issuer API over JavaScript to bake this badge and put it in my backpack. Here's the hosted assertion:

``` json
{
    "uid": "ottonomy-the-swindler-1",
    "recipient": {
        "type": "email",
        "hashed": true,
        "salt": "coarsekosher",
        "identity": "sha256$ff80caeeea3342f16692d99dfe4c0d4c426be3c69d86948c3e91aa5ca52f6208"
    },
    "issuedOn": "2014-01-03T21:42:21.092Z",
    "badge": "http://ottonomy.net/manualbadges/badgeclass-badge-swindler.json",
    "verify": {
        "type": "hosted",
        "url": "http://gator3046.hostgator.com/~ottonomy/manualbadges/assertions/swindler/ottonomy-the-swindler-1.json"
    }
}
```

Then I downloaded the badge from my backpack collection. The assertion baked into the badge by the Issuer API is this:

``` json
{
    "uid": "ottonomy-the-swindler-1",
    "recipient": "sha256$ff80caeeea3342f16692d99dfe4c0d4c426be3c69d86948c3e91aa5ca52f6208",
    "issuedOn": "2014-01-03T21:42:21.092Z",
    "badge": {
        "name": "Master Badge Swindler",
        "description": "This user has created their own properly formed Open Badge by hand, except that reputable upstanding organization ottonomy.net surely wouldn't ever issue such a badge. If you're seeing this badge in someone's backpack, it means they're a master badge swindler. Can you figure out how they did it?",
        "image": "http://ottonomy.net/manualbadges/badge-swindler.png",
        "criteria": "http://ottonomy.net/manualbadges/swindler-badge-criteria.html",
        "issuer": {
            "name": "Nate Otto",
            "url": "http://ottonomy.net",
            "description": "Personal website of Nate Otto",
            "email": "badgeissuer@ottonomy.net",
            "_location": "http://ottonomy.net/manualbadges/issuer.json",
            "origin": "http://ottonomy.net"
        },
        "_location": "http://ottonomy.net/manualbadges/badgeclass-badge-swindler.json"
    },
    "verify": {
        "type": "hosted",
        "url": "http://gator3046.hostgator.com/~ottonomy/manualbadges/assertions/swindler/ottonomy-the-swindler-1.json"
    },
    "_originalRecipient": {
        "type": "email",
        "hashed": true,
        "salt": "coarsekosher",
        "identity": "sha256$ff80caeeea3342f16692d99dfe4c0d4c426be3c69d86948c3e91aa5ca52f6208"
    },
    "salt": "coarsekosher",
    "issued_on": "2014-01-03T21:42:21.092Z"
}
```

Excepting for a validation error because I used a full timestamp instead of just YYYY-MM-DD this badge passes the [Validator](http://validator.openbadges.org/), but says that it's passing on the 0.5 spec path, not the 1.0 spec path, as I had originally asserted the badge. You can see some differences: for example, look at the recipient field of the assertion. It has been flattened to 0.5 style.

I find this kind of strange. Had an unrelated error with a baked badge that led me down this path of exploration.

CC: @brianloveswords, @cmcavoy @threeqube

**Comment by smartcodingxx** [comment]
Hi ottonomy,
I don't know I have to ask the question here or somewhere else. Sorry in advance. but its related to baking badges. 

Do assertion data .json file and verify .json file will have same data ?

here is the detail 

- assertion json file
`{
	"uid" : "85ca1973771769c4b3eef0156b607b58f0651bee",
	"recipient" : {
		"identity" : "sha256$094ac2d2c5195904dfdb2511e6d9937b7a871e8b2d339215bc14cb346f43732a",
		"type" : "email",
		"hashed" : true
	},
	"badge" : "http://localhost:8888/content/badge.json",
	"verify" : {
		"url" : "http://localhost:8888/content/verify.json",
		"type" : "hosted"
	},
	"issuedOn" : 1466060644
}`

- badge json file
`{
	"name" : "Mozilla Badge",
	"description" : "description here",
	"image" : "http://localhost:8888/content/demo-badge.png",
	"criteria" : "http://localhost:8888/backpack/login",
	"alignment" : [],
	"issuer" : "http://localhost:8888/content/issuer.json"
}`

- issuer json file
`{"name":"My Own Badge System","url":"http://localhost:8081"}`

- verify

 json file (Following above commented json data - commented on Aug 8, 2014)
`{
	"uid" : "85ca1973771769c4b3eef0156b607b58f0651bee",
	"recipient" : {
		"identity" : "sha256$094ac2d2c5195904dfdb2511e6d9937b7a871e8b2d339215bc14cb346f43732a",
		"type" : "email",
		"hashed" : true
	},
	"badge" : "http://localhost:8888/content/badge.json",
	"verify" : {
		"url" : "http://localhost:8888/content/verify.json",
		"type" : "hosted"
	},
	"issuedOn" : 1466060644
}`


By passing assertion to bakerAPI I getting following error

_"name" : "openbadges-backpack",
	"hostname" : "GYRUS-221",
	"pid" : 5616,
	"level" : 60,
	"err"
	 : {
		"message" : "Method Uint8Array.length called on incompatible receiver [object Ob
		ject]",
		"name" : "TypeError",
		"stack" : "TypeError: Method Uint8Array.length called on
		 incompatible receiver [object Object]\n    at BitWriter.get length (native)\n
		  at BitWriter.makeArrayLike [as _makeArrayLike] (D:\\_


then I follow the [Assertion Information for the Uninitiated](https://github.com/mozilla/openbadges-backpack/wiki/Assertion-Information-for-the-Uninitiated#verification-object) link. 

As per link the verify object should have only **_type_** and **_URL_**. 
So I change the verify json to as follows...
`{
	"type": "hosted",
	"url":"http://localhost:8081/public/assertions/85ca1973771769c4b3eef0156b607b58f0651bee"
}`
and I am getting following error which indicates that assertion and verify data should match.

`{
	"message" : "Remote assertion must match local assertion",
	"stack" : "Error: Remote assertion must match local assertion\n    at makeError (D:\\Dharmendra\\11_Published\\badgeBaker\\node_modules\\openbadges-validator\\index.js:495:15)\n    at validateHosted (D:\\Dharmendra\\11_Published\\badgeBaker\\node_modules\\openbadges-validator\\index.js:436:25)\n    at fn (D:\\Dharmendra\\11_Published\\badgeBaker\\node_modules\\async\\lib\\async.js:582:34)\n    at Immediate._onImmediate (D:\\Dharmendra\\11_Published\\badgeBaker\\node_modules\\async\\lib\\async.js:498:34)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)",
	"code" : "verify-hosted",
	"extra" : {
		"local" : {
			"uid" : "85ca1973771769c4b3eef0156b607b58f0651bee",
			"recipient" : {
				"identity" : "sha256$094ac2d2c5195904dfdb2511e6d9937b7a871e8b2d339215bc14cb346f43732a",
				"type" : "email",
				"hashed" : true
			},
			"badge" : "http://localhost:8888/content/badge.json",
			"verify" : {
				"url" : "http://localhost:8888/content/verify.json",
				"type" : "hosted"
			},
			"issuedOn" : 1466060644
		},
		"hosted" : {
			"type" : "hosted",
			"url" : "http://localhost:8081/public/assertions/85ca1973771769c4b3eef0156b607b58f0651bee"
		}
	}
}
`
For your information I have hosted two node js api's

1. **http://localhost:8081** - **_BadgeKit API_** where I am creating and awarding badges.
2. **http://localhost:8888** - **_openbadges-backpack_** where I am using baker API to bake images.

OS: Windows 7 pro 64bit

Any hint or suggestion regarding this?
Thank you in advance,
Dharmendra mistry

**Comment by smartcodingxx** [comment]
I am able to solve baking issue by using compatible node js version.

The app (openbadges-backpack) is using engine _**0.10.30**_ while I am using latest **_4.4.5._** So I need to downgrade node js version and it works like charm.

Also I found that assertion json file data and verify json file data must be same in case of hosted type.

Hope this help someone.

Thanks

**Comment by mattdigitalme** [comment]
@auralon @ottonomy This would be one to check with the update and Issuer API - if not, we should definitely look into this

**Comment by auralon** [comment]
There is certainly further development required in order to support newer badge specs properly.
