### ISSUE TITLE
Database collation / encoding issue

### ISSUE THREAD

**Issue by DavidBenko** [mozilla/openbadges-backpack#1076]
Getting the following error when hitting the connect API at either `GET /identity` or `POST /issue` on https://backpack.openbadges.org/api/:

```
Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_unicode_ci,COERCIBLE) for operation '='
    at Function.Client._packetToUserObject (/app/node_modules/mysql/lib/client.js:394:11)
    at Query._handlePacket (/app/node_modules/mysql/lib/query.js:33:33)
    at Client._handlePacket (/app/node_modules/mysql/lib/client.js:319:14)
    at Parser.emit (events.js:95:17)
    at emitPacket (/app/node_modules/mysql/lib/parser.js:71:14)
    at Parser.write (/app/node_modules/mysql/lib/parser.js:576:7)
    at Socket.emit (events.js:95:17)
    at Socket.
<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
```

**Comment by mattdigitalme** [comment]
@auralon 

@DavidBenko Do you want to join the [Backpack Developer Slack Channel](https://www.google.com/url?q=https%3A%2F%2Fbackpackng.slack.com%2Finvite%2FMTEyNDk3MDg1NjM4LTE0ODA2NzU0NzItODQ4MDBhOTE3ZQ&sa=D&sntz=1&usg=AFQjCNFNAJl0Dyf2rsl7s1-3RtUrTRYyiw) to get this worked through
