### ISSUE TITLE
Error when trying to post a badge to the backpack

### ISSUE THREAD

**Issue by RobTrainer** [mozilla/openbadges-backpack#1114]
GET https://backpack.openbadges.org/issuer/[[assertion.badge.image]] 404 (Not Found)

This message is displayed in the browser console when the Backpack Login or Badge Send popup is displayed.

Secondarily, after clicking Login or Send, the popup displays nothing and the badge is not posted to the backpack.

**Comment by auralon** [comment]
[Dupe](https://github.com/mozilla/openbadges-backpack/issues/749)

**Comment by auralon** [comment]
[Dupe](https://github.com/mozilla/openbadges-backpack/issues/749)

The popup displaying nothing is probably unrelated, but is still something to be investigated.

What browser/os and versions are you using?

**Comment by RobTrainer** [comment]
Windows 10/Chrome 55.0.2883.87
Windows 10/firefox 50.0.2

**Comment by RobTrainer** [comment]
Has anyone had a chance to look at this issue?

**Comment by auralon** [comment]
Hi @RobTrainer.  It's on the radar, but I've not had chance to look at this yet.

**Comment by RobTrainer** [comment]
I spun up a copy of the backpack to see if the problem is on our side. What I found was that the badges that I was posting had a link to the assertion that did not resolve. Upon using a new badge, the backpack prompted me for confirmation to accept the badge.

At this point, I get the following:

{  
   "name":"openbadges-backpack",
   "hostname":"dev-backpack",
   "pid":12156,
   "level":30,
   "req":{  
      "method":"POST",
      "url":"/issuer/assertion",
      "headers":{  
         "host":"backpack.badgesafe.net",
         "connection":"keep-alive",
         "content-length":"113",
         "accept":"*/*",
         "origin":"https://backpack.badgesafe.net",
         "x-csrf-token":"2lV7aNBO-vPk_snWY0rnb0GBxA_pPv0C7XLA",
         "x-requested-with":"XMLHttpRequest",
         "user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36",
         "content-type":"application/x-www-form-urlencoded; charset=UTF-8",
         "referer":"https://backpack.badgesafe.net/issuer/frame?1482240910419",
         "accept-encoding":"gzip, deflate, br",
         "accept-language":"en-US,en;q=0.8,id;q=0.6",
         "cookie":"session=eyJjc3JmU2VjcmV0IjoiWmxoMjE2X1pSa3FxbW5QOVBvR2ZUbXVIIiwiZmxhc2giOnt9LCJwYXNzcG9ydCI6eyJ1c2VyIjoyfX0=; session.sig=hAJYPv6Mx2iOdy5zWC1dn1kaT2U; gsScrollPos=0"
      },
      "remoteAddress":"::ffff:108.40.123.240",
      "remotePort":54502
   },
   "msg":"Incoming Request: POST /issuer/assertion",
   "time":"2016-12-20T13:36:09.516Z",
   "v":0
}

{"name":"openbadges-backpack","hostname":"dev-backpack","pid":12156,"level":60,"err":{"message":"Method get TypedArray.prototype.length called on incompatible receiver [object Object]","name":"TypeError","stack":"TypeError: Method get TypedArray.prototype.length called on incompatible receiver [object Object]\n    at BitWriter.get length [as length] (native)\n    at BitWriter.makeArrayLike [as _makeArrayLike] (/root/openbadges-backpack/node_modules/bitwriter/index.js:357:17)\n    at BitWriter.setupBuffer (/root/openbadges-backpack/node_modules/bitwriter/index.js:72:8)\n    at BitWriter.initialize (/root/openbadges-backpack/node_modules/bitwriter/index.js:58:8)\n    at new BitWriter (/root/openbadges-backpack/node_modules/bitwriter/index.js:10:19)\n    at BitWriter (/root/openbadges-backpack/node_modules/bitwriter/index.js:9:12)\n    at new Output (/root/openbadges-backpack/node_modules/streampng/lib/chunks/base.js:161:17)\n    at constructor.outputPrepare [as _outputPrepare] (/root/openbadges-backpack/node_modules/streampng/lib/chunks/base.js:155:13)\n    at constructor.makeBuffer [as _startOutput] (/root/openbadges-backpack/node_modules/streampng/lib/chunks/international-text.js:38:21)\n    at constructor.out (/root/openbadges-backpack/node_modules/streampng/lib/chunks/international-text.js:23:19)"},"msg":"Method get TypedArray.prototype.length called on incompatible receiver [object Object]","time":"2016-12-20T13:36:09.666Z","v":0}
/root/openbadges-backpack/node_modules/messina/index.js:40
      throw err;
      ^

TypeError: Method get TypedArray.prototype.length called on incompatible receiver [object Object]
    at BitWriter.get length [as length] (native)
    at BitWriter.makeArrayLike [as _makeArrayLike] (/root/openbadges-backpack/node_modules/bitwriter/index.js:357:17)
    at BitWriter.setupBuffer (/root/openbadges-backpack/node_modules/bitwriter/index.js:72:8)
    at BitWriter.initialize (/root/openbadges-backpack/node_modules/bitwriter/index.js:58:8)
    at new BitWriter (/root/openbadges-backpack/node_modules/bitwriter/index.js:10:19)
    at BitWriter (/root/openbadges-backpack/node_modules/bitwriter/index.js:9:12)
    at new Output (/root/openbadges-backpack/node_modules/streampng/lib/chunks/base.js:161:17)
    at constructor.outputPrepare [as _outputPrepare] (/root/openbadges-backpack/node_modules/streampng/lib/chunks/base.js:155:13)
    at constructor.makeBuffer [as _startOutput] (/root/openbadges-backpack/node_modules/streampng/lib/chunks/international-text.js:38:21)
    at constructor.out (/root/openbadges-backpack/node_modules/streampng/lib/chunks/international-text.js:23:19)

One other thing to note is that I can bake the same badge and successfully upload it to the backpack.

**Comment by Starli0n** [comment]
I have the same issue just after the backpack popup invites you to send your badge (ie: popup with the send button)

After I have the issue, described at #1126

I have the same issue on Win/Mac, Firefox/IE

**Comment by MuhRizal** [comment]
I have similar issue.
Downgrade the node version to 0.10 using nvm solves my problem.

**Comment by afconceglieri** [comment]
Same issue... 
node version is 6.9.4, some hint?

**Comment by akshayporwal** [comment]
Same issue...
GET https://backpack.openbadges.org/issuer/[[assertion.badge.image]] 404 (Not Found)
VM277 jquery.min.js:4 GET https://backpack.openbadges.org/issuer/assertion?assertion=http....json 400 (Bad Request)
node version is 9.5.0 some hint?
