### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by fouloleron** [mozilla/openbadges-backpack#1182]
When attempting to log in via https://backpack.openbadges.org/backpack/login receive the message:
```
Error: Cannot enqueue Query after fatal error.
   at Protocol._validateEnqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:199:16)
   at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:135:13)
   at Connection.query (/app/node_modules/mysql/lib/Connection.js:208:25)
   at Function.find (/app/models/mysql-base.js:48:12)
   at Function.Model.findOne (/app/models/mysql-base.js:52:11)
   at /app/auth/passport.js:147:18
   at process._tickCallback (node.js:458:13)
```
This error did not appear yesterday; I was able to log in the last time I tried, approximately 24 hours ago.

Using Chrome Version 71.0.3578.127 (Official Build) (64-bit).

**Comment by LennyObez** [comment]
Same issue while attempting to sign in via [backpack.openbadges.org/backpack/login](https://backpack.openbadges.org/backpack/signup) 👍 
```
Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:199:16)
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:135:13)
    at Connection.query (/app/node_modules/mysql/lib/Connection.js:208:25)
    at Function.find (/app/models/mysql-base.js:48:12)
    at Function.Model.findOne (/app/models/mysql-base.js:52:11)
    at /app/auth/passport.js:250:22
    at process._tickCallback (node.js:458:13)
```
Using Chrome Version 72.0.3626.121 (Official Build) (64-bit).

**Comment by dmitryshagin** [comment]
It works and fails randomly. I was able to log in last week and it does not work in the same way for a whole day today.

**Comment by klenert2** [comment]
I also was able to log in last week and not today. Password reset not working i.e. says no such email address. Right before I was going to do a demo.  I had uploaded digital badges created in Blackboard Open LMS to my backpack. But don't want to recommend backpack if functioning is unreliable or the site is no longer in use.  Hard to find answers! Thanks

**Comment by lrsmith2** [comment]
I am getting this error after having filled out my backpack and built out my presentation successfully for stakeholders this weekend on how it is supposed to work in Totara and Moodle:

Error: Cannot enqueue Query after fatal error. at Protocol._validateEnqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:199:16) at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:135:13) at Connection.query (/app/node_modules/mysql/lib/Connection.js:208:25) at Function.find (/app/models/mysql-base.js:48:12) at Function.Model.findOne (/app/models/mysql-base.js:52:11) at /app/auth/passport.js:147:18 at process._tickCallback (node.js:458:13)

It is happening in both Chrome and Firefox, latest stable versions.

Thinking I had forgotten my pw, I tried to reset it. At first, it said my account did not exist. Then it allowed me to reset it. Then I tried to log in with the new pw and continued to get this error. Since others say this is random, I guess I will wait to see if it resolves itself? :-(
<img width="1457" alt="Screen Shot 2019-04-23 at 11 57 01 AM" src="https://user-images.githubusercontent.com/13125337/56601528-00eaeb80-65c1-11e9-9ad9-eda8bc1249c2.png">

**Comment by lrsmith2** [comment]
It is working again today. I didn't even have to clear cache or history, so I am hoping that means it is fixed permanently. Thanks!

**Comment by izendegi** [comment]
I'm also having this error when trying to log in, so it hasn't been definitively fixed yet.

**Comment by learningpal** [comment]
I'm getting this error too.
